name: HyperSpecies
version: '${project.version}'
main: net.toujoustudios.hyperspecies.main.HyperSpecies
api-version: 1.19
author: Toujou Studios
authors:
  - IanToujou

commands:
  emote:
    description: Use an emote on yourself or another player.
    permission: hyperspecies.command.emote
    aliases:
      - e
  emotelist:
    description: Show a list of all the emotes available.
    permission: hyperspecies.command.emotelist

permissions:
  hyperspecies.group.player:
    description: The player group.
    children:
      hyperspecies.command.emote: true
      hyperspecies.command.emotelist: true
  hyperspecies.group.admin:
    description: The administrator group. Grants all permissions.
    children:
      hyperspecies.command.emote: true
      hyperspecies.command.emotelist: true
  hyperspecies.command.emote:
    description: Allows players to use the emote command.
    default: true
  hyperspecies.command.emotelist:
    description: Allows players to use the emotelist command.
    default: true