name: HyperSpecies
version: '${project.version}'
main: net.toujoustudios.hyperspecies.main.HyperSpecies
api-version: 1.20
author: Toujou Studios
authors:
  - IanToujou

commands:
  emote:
    description: Use an emote on yourself or another player.
    permission: hyperspecies.command.emote
    aliases:
      - e
  emotelist:
    description: Show a list of all the emotes available.
    permission: hyperspecies.command.emotelist
    aliases:
      - elist
  team:
    description: Show and manage your team.
    permission: hyperspecies.command.team
  ability:
    description: Use an ability by force.
    permission: hyperspecies.command.ability
  reset:
    description: Reset your character, losing all of your progress.
    permission: hyperspecies.command.reset
  loadout:
    description: Open up the ability tree.
    permission: hyperspecies.command.loadout
    aliases:
      - lo
  setshield:
    description: Set the shield value for a player.
    permission: hyperspecies.command.setshield
  sethealth:
    description: Set the health value for a player.
    permission: hyperspecies.command.sethealth
  setmana:
    description: Set the mana value for a player.
    permission: hyperspecies.command.setmana
  setspecies:
    description: Set the species for a player.
    permission: hyperspecies.command.setspecies
  unlock:
    description: Unlock the ability for a player.
    permission: hyperspecies.command.unlock
  setskill:
    description: Set the skill points for a player.
    permission: hyperspecies.command.setskill
  setexperience:
    description: Set the experience for a player.
    permission: hyperspecies.command.setexperience
  character:
    description: View your character.
    permission: hyperspecies.command.character
    aliases:
      - char
  leave:
    description: Leave the farmworld.
    permission: hyperspecies.command.leave
  passive:
    description: Enable and disable the passives.
    permission: hyperspecies.command.passive

permissions:
  hyperspecies.group.player:
    description: The player group.
    children:
      hyperspecies.command.emote: true
      hyperspecies.command.emotelist: true
      hyperspecies.command.team: true
      hyperspecies.command.ability: false
      hyperspecies.command.reset: true
      hyperspecies.command.loadout: false
      hyperspecies.command.setshield: false
      hyperspecies.command.sethealth: false
      hyperspecies.command.setmana: false
      hyperspecies.command.setspecies: false
      hyperspecies.command.unlock: false
      hyperspecies.command.setskill: false
      hyperspecies.command.setexperience: false
      hyperspecies.command.character: true
      hyperspecies.command.leave: true
      hyperspecies.command.passive: false
  hyperspecies.group.admin:
    description: The administrator group. Grants all permissions.
    children:
      hyperspecies.command.emote: true
      hyperspecies.command.emotelist: true
      hyperspecies.command.team: true
      hyperspecies.command.ability: true
      hyperspecies.command.reset: true
      hyperspecies.command.loadout: true
      hyperspecies:command.setshield: true
      hyperspecies.command.sethealth: true
      hyperspecies.command.setmana: true
      hyperspecies.command.setspecies: true
      hyperspecies.command.unlock: true
      hyperspecies.command.setskill: true
      hyperspecies.command.setexperience: true
      hyperspecies.command.character: true
      hyperspecies.command.leave: true
      hyperspecies.command.passive: true
  hyperspecies.group.moderator:
    description: The administrator group. Grants all permissions.
    children:
      hyperspecies.command.emote: true
      hyperspecies.command.emotelist: true
      hyperspecies.command.team: true
      hyperspecies.command.ability: false
      hyperspecies.command.reset: true
      hyperspecies.command.loadout: false
      hyperspecies.command.setshield: false
      hyperspecies.command.sethealth: false
      hyperspecies.command.setmana: false
      hyperspecies.command.setspecies: false
      hyperspecies.command.unlock: false
      hyperspecies.command.setskill: false
      hyperspecies.command.setexperience: false
      hyperspecies.command.character: true
      hyperspecies.command.leave: true
      hyperspecies.command.passive: false
  hyperspecies.command.emote:
    description: Allows players to use the emote command.
    default: true
  hyperspecies.command.emotelist:
    description: Allows players to use the emotelist command.
    default: true
  hyperspecies.command.team:
    description: Allows players to use the team command.
    default: true
  hyperspecies.command.ability:
    description: Allows players to use the ability command.
    default: op
  hyperspecies.command.reset:
    description: Allows players to use the reset command.
    default: true
  hyperspecies.command.loadout:
    description: Allows players to use the ability tree command.
    default: op
  hyperspecies.command.setshield:
    description: Allows players to use the set shield command.
    default: op
  hyperspecies.command.sethealth:
    description: Allows players to use the set health command.
    default: op
  hyperspecies.command.setmana:
    description: Allows players to use the set mana command.
    default: op
  hyperspecies.command.setspecies:
    description: Allows players to use the set species command.
    default: op
  hyperspecies.command.unlock:
    description: Allows players to use the unlock command.
    default: op
  hyperspecies.command.setskill:
    description: Allows players to use the set skill command.
    default: op
  hyperspecies.command.setexperience:
    description: Allows players to use the set experience command.
    default: op
  hyperspecies.command.character:
    description: Allows players to use the character command.
    default: true
  hyperspecies.command.leave:
    description: Allows players to use the leave command.
    default: true
  hyperspecies.command.passive:
    description: Allows players to use the passive command.
    default: op