name: HyperSpecies
version: '${project.version}'
main: net.toujoustudios.hyperspecies.main.HyperSpecies
api-version: 1.19
author: Toujou Studios
authors:
  - IanToujou

commands:
  emote:
    description: Use an emote on yourself or another player.
    permission: hyperspecies.command.emote
    aliases:
      - e
  emotelist:
    description: Show a list of all the emotes available.
    permission: hyperspecies.command.emotelist
    aliases:
      - elist
  team:
    description: Show and manage your team.
    permission: hyperspecies.command.team
  ability:
    description: Use an ability by force.
    permission: hyperspecies.command.ability
  reset:
    description: Reset your character, losing all of your progress.
    permission: hyperspecies.command.reset
  tree:
    description: Open up the ability tree.
    permission: hyperspecies.command.tree

permissions:
  hyperspecies.group.player:
    description: The player group.
    children:
      hyperspecies.command.emote: true
      hyperspecies.command.emotelist: true
      hyperspecies.command.team: true
      hyperspecies.command.ability: false
      hyperspecies.command.reset: true
      hyperspecies.command.tree: true
  hyperspecies.group.admin:
    description: The administrator group. Grants all permissions.
    children:
      hyperspecies.command.emote: true
      hyperspecies.command.emotelist: true
      hyperspecies.command.team: true
      hyperspecies.command.ability: true
      hyperspecies.command.reset: true
      hyperspecies.command.tree: true
  hyperspecies.group.moderator:
    description: The administrator group. Grants all permissions.
    children:
      hyperspecies.command.emote: true
      hyperspecies.command.emotelist: true
      hyperspecies.command.team: true
      hyperspecies.command.ability: false
      hyperspecies.command.reset: true
      hyperspecies.command.tree: true
  hyperspecies.command.emote:
    description: Allows players to use the emote command.
    default: true
  hyperspecies.command.emotelist:
    description: Allows players to use the emotelist command.
    default: true
  hyperspecies.command.team:
    description: Allows players to use the team command.
    default: true
  hyperspecies.command.ability:
    description: Allows players to use the ability command.
    default: op
  hyperspecies.command.reset:
    description: Allows players to use the reset command.
    default: true
  hyperspecies.command.tree:
    description: Allows players to use the tree command.
    default: true