name: HyperSpecies
version: '${project.version}'
main: net.toujoustudios.hyperspecies.main.HyperSpecies
api-version: 1.20
author: Toujou Studios
authors:
  - IanToujou

commands:
  emote:
    description: Use an emote on yourself or another player.
    permission: hyperspecies.command.emote
    aliases:
      - e
  emotelist:
    description: Show a list of all the emotes available.
    permission: hyperspecies.command.emotelist
    aliases:
      - elist
  team:
    description: Show and manage your team.
    permission: hyperspecies.command.team
  ability:
    description: Use an ability by force.
    permission: hyperspecies.command.ability
  reset:
    description: Reset your character, losing all of your progress.
    permission: hyperspecies.command.reset
  abilitytree:
    description: Open up the ability tree.
    permission: hyperspecies.command.abilitytree
  shield:
    description: Set the shield value for a player.
    permission: hyperspecies.command.shield
  health:
    description: Set the health value for a player.
    permission: hyperspecies.command.health
  mana:
    description: Set the mana value for a player.
    permission: hyperspecies.command.mana
  species:
    description: Set the species for a player.
    permission: hyperspecies.command.species
  unlock:
    description: Unlock the ability for a player.
    permission: hyperspecies.command.unlock

permissions:
  hyperspecies.group.player:
    description: The player group.
    children:
      hyperspecies.command.emote: true
      hyperspecies.command.emotelist: true
      hyperspecies.command.team: true
      hyperspecies.command.ability: false
      hyperspecies.command.reset: true
      hyperspecies.command.abilitytree: true
      hyperspecies.command.shield: false
      hyperspecies.command.health: false
      hyperspecies.command.mana: false
      hyperspecies.command.species: false
      hyperspecies.command.unlock: false
  hyperspecies.group.admin:
    description: The administrator group. Grants all permissions.
    children:
      hyperspecies.command.emote: true
      hyperspecies.command.emotelist: true
      hyperspecies.command.team: true
      hyperspecies.command.ability: true
      hyperspecies.command.reset: true
      hyperspecies.command.abilitytree: true
      hyperspecies:command.shield: true
      hyperspecies.command.health: true
      hyperspecies.command.mana: true
      hyperspecies.command.species: true
      hyperspecies.command.unlock: true
  hyperspecies.group.moderator:
    description: The administrator group. Grants all permissions.
    children:
      hyperspecies.command.emote: true
      hyperspecies.command.emotelist: true
      hyperspecies.command.team: true
      hyperspecies.command.ability: false
      hyperspecies.command.reset: true
      hyperspecies.command.abilitytree: true
      hyperspecies.command.shield: false
      hyperspecies.command.health: false
      hyperspecies.command.mana: false
      hyperspecies.command.species: false
      hyperspecies.command.unlock: false
  hyperspecies.command.emote:
    description: Allows players to use the emote command.
    default: true
  hyperspecies.command.emotelist:
    description: Allows players to use the emotelist command.
    default: true
  hyperspecies.command.team:
    description: Allows players to use the team command.
    default: true
  hyperspecies.command.ability:
    description: Allows players to use the ability command.
    default: op
  hyperspecies.command.reset:
    description: Allows players to use the reset command.
    default: true
  hyperspecies.command.abilitytree:
    description: Allows players to use the abilitytree command.
    default: true
  hyperspecies.command.shield:
    description: Allows players to use the shield command.
    default: op
  hyperspecies.command.health:
    description: Allows players to use the health command.
    default: op
  hyperspecies.command.mana:
    description: Allows players to use the mana command.
    default: op
  hyperspecies.command.species:
    description: Allows players to use the species command.
    default: op
  hyperspecies.command.unlock:
    description: Allows players to use the unlock command.
    default: op