# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Hyper Species
extra_css:
  - css/main.css
theme:
  language: en
  name: material
  palette:
    scheme: slate
    primary: orange
    accent: deep orange